apiVersion: v1
kind: PersistentVolume
metadata:
  name: flask-pv
  labels:
    type: nfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path:  /srv/nfs/wanes         #your MiamiID
    server: 10.48.10.140
  persistentVolumeReclaimPolicy: Retain
