apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flask-pvc    
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      type: nfs
